# 存储配置
[storage]
# 文件根目录
file_root_dir = "/Users/aoe/aoemedia-server-storage/dev/files"
# 图片根目录
image_root_dir = "/Users/aoe/aoemedia-server-storage/dev/images"

# 数据库配置
[database]
driver = "mysql"
host = "localhost"
port = 3306
username = "root"
password = "root123456"
dbname = "media"
charset = "utf8mb4"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = "1h"