# 存储配置
[storage]
# 文件根目录
file_root_dir = "temp-test-files"
# 图片根目录
image_root_dir = "temp-test-images"
# 图片访问路径前缀
image_url_prefix = "http://localhost:8080/images/"

# 数据库配置
[database]
driver = "mysql"
host = "localhost"
port = 3306
username = "root"
password = "root123456"
dbname = "media"
charset = "utf8mb4"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = "1h"

# 用户列表
[[users]]
token = "a"
id = 1

[[users]]
token = "b"
id = 2