# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set timezone
      run: sudo timedatectl set-timezone Asia/Shanghai

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'media'
        mysql root password: 'root123456'

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h127.0.0.1 -P3306 -uroot -proot123456 --silent; do
          sleep 1
        done

    - name: Create database tables
      run: |
        mysql --defaults-extra-file=<(echo -e "[client]\nhost=127.0.0.1\nuser=root\npassword=root123456\n") media < docs/sql/create_tables.sql

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile=coverage.txt

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
